spring:
  application:
    name: matrix-customer
  server:
    port: 9001
server:
  port: 9001
  
client:
  request:
    interval: 5000
    
order:
  dispatcher:
    url: http://matrix-order-dispatcher:9002/order/{itemName}
